export const TeamMembers = [
  {
    id: 1,
    name: "S. Suresh Suryavanshi",
    role: "Chief Executive Officer",
    image: "/team/surya.jpg",
  },
  {
    id: 2,
    name: "Ashwinth Kumar",
    role: "Head of communications",
    image: "/team/ashwinth.jpg",
  },
  {
    id: 3,
    name: "Shreejith Shashi",
    role: "Head of Production and Creative",
    image: "/team/sreejith.jpg",
  },
  {
    id: 4,
    name: "Milan K Manoj",
    role: "Creative Head",
    image: "/team/milan.jpg",
  },
  {
    id: 5,
    name: "Diwakar Chavan",
    role: "Head of Digital Marketing",
    image: "/team/divakar.jpg",
  },
  {
    id: 6,
    name: "Nishitha Mariam George",
    role: "Creative Director",
    image: "/team/nisitha.jpg",
  },
  {
    id: 7,
    name: "Varun Kaladharan",
    role: "Director of Photography",
    image: "/team/varun.jpg",
  },
  {
    id: 8,
    name: "Sharath Raam Prasad",
    role: "Creative Director",
    image: "/team/sharath.jpg",
  },
  {
    id: 9,
    name: "Tanya Bhatnagar",
    role: "Production Manager",
    image: "/team/tanya.jpg",
  },
  {
    id: 10,
    name: "Rahul Kuttappy",
    role: "Chief Editor",
    image: "/team/rahul.jpg",
  },
  {
    id: 11,
    name: "Rohith Baburaj",
    role: "Photographer",
    image: "/team/rohith.jpg",
  },
  {
    id: 12,
    name: "Kavana",
    role: "Business Developer",
    image: "/team/kavana.jpg",
  },
];

export const Projects = [
  {
    id: 1,
    title: "Umber",
    caption: "Crafting Timeless Elegance",
    slug: "umber",
    about:
      "Our partnership with Umber was all about the details. Through each carefully framed shot, we captured the essence of their furniture, celebrating both functionality and craftsmanship in a way that speaks to the brand’s dedication to quality.",
    services: ["Product Photography", "Videography"],
    description1:
      " As the first team to work with Umber, we captured the brand’s philosophy through product launch visuals, creating photos and videos that highlight their blend of traditional craftsmanship and modern design.",
    description2:
      "Each frame embodies Umber’s commitment to blending Indian elegance with everyday functionality.We stood committed to delivering content that resonated emotionally and culturally, by bringing their stories to life .",
    bannerImageDesktop: "/projects/Umber/Umber_banner 2.jpg",
    bannerImageMobile: "/projects/Umber_1.jpg",
    aboutImage1: "/projects/Umber/1.jpg",
    aboutImage2: "/projects/Umber/3.jpg",
    marqueeImage: [
      "/projects/Umber/marque_1.jpg",
      "/projects/Umber/marque_2.jpg",
      "/projects/Umber/marque_3.jpg",
      "/projects/Umber/marque_4.jpg",
      "/projects/Umber/marque_5.jpg",
      "/projects/Umber/marque_6.png",
    ],
    btsImages: [
      "/projects/Umber/bts/01.jpg",
      "/projects/Umber/bts/02.jpg",
      "/projects/Umber/bts/03.jpg",
      "/projects/Umber/bts/04.jpg",
      "/projects/Umber/bts/05.jpg",
      "/projects/Umber/bts/06.jpg",
    ],
  },
  {
    id: 2,
    className: " bg-[#2617A5D]",
    title: "11grams",
    caption: "Aromatic Scenes, Crafted Beans",
    slug: "11grams",
    about:
      "Crafting each shot as an invitation to indulge in the café’s mouth-watering delicacies , our collaboration with 11 Grams brought to light the warmth and charm of their café experience.",
    services: ["Food Photography", "Videography"],
    description1:
      "From capturing the essence of their vibrant coffee culture , diverse menu and the rarest coffee beans in Bangalore through our frames , we created content that resonated with customers by aligning with their brand palette.",
    description2:
      " Our work extended to influencer marketing and the cafe’s inauguration, establishing a memorable brand presence.",
    bannerImageDesktop: "/projects/11grams/11gram_banner.png",
    bannerImageMobile: "/projects/11grams/11 Grams_Banner vertical.jpg",
    aboutImage1: "/projects/11grams/1.png",
    aboutImage2: "/projects/11grams/2.png",
    mobileVideos: ["/projects/11grams/1.mp4", "/projects/11grams/2.mp4"],
    marqueeImage: [
      "/projects/11grams/marque_1.jpg",
      "/projects/11grams/marque_2.jpg",
      "/projects/11grams/marque_3.jpg",
      "/projects/11grams/marque_4.jpg",
      "/projects/11grams/marque_5.jpg",
      "/projects/11grams/marque_6.jpg",
    ],
    btsImages: [
      "/projects/11grams/bts/11.jpg",
      "/projects/11grams/bts/12.jpg",
      "/projects/11grams/bts/13.jpg",
      "/projects/11grams/bts/14.jpg",
      "/projects/11grams/bts/15.jpg",
      "/projects/11grams/bts/13.jpg",
    ],
  },
  {
    id: 3,
    className: " bg-[#262525]",
    title: "Fashion",
    caption: "Elevate Your Brand with Distinctive Fashion Imagery",
    slug: "fashion",
    about:
      "At FFM, we bring unparalleled quality to every shoot, blending creativity with precision to capture the essence of style. Our team focuses on the finest details—from lighting to composition—to ensure each shot reflects the highest standards of fashion excellence. With our expertise and passion, we create stunning visuals that elevate your brand and leave a lasting impact.",
    services: [
      "Advertisements",
      "Fashion Campaigns",
      "Editorial Fashion",
      "Jewellery Campaigns",
      "Catalogue",
      "Lifestyle",
      "Social Media Contents",
      "Portraits",
      "High Fashion",
      "Products",
    ],
    description1:
      "From high-fashion campaigns to lifestyle shoots, we bring your brand’s vision to life through striking, high-quality imagery. Our expertise spans advertisements, editorial fashion, jewelry campaigns, catalogs, social media content, and more. Whether it's a captivating portrait or an engaging product showcase, we create visuals that make a lasting impact and resonate with your audience.",
    description2:
      "We create impactful fashion imagery—ads, campaigns, editorial, and lifestyle content—that captures your brand’s unique style and vision.",
    bannerImageDesktop: "/projects/fashion/fashion_banner.jpg",
    bannerImageMobile: "/hero-banner-4.jpg",
    aboutImage1: "/projects/fashion/1.jpg",
    aboutImage2: "/projects/fashion/2.png",
    desktopVideos: [
      "/projects/fashion/Fashion_1.mp4",
      "/projects/fashion/Fashion_2.mp4",
      "/projects/fashion/Fashion_3.mp4",
      "/projects/fashion/Fashion_4.mp4",
    ],
    marqueeImage: [
      "/projects/fashion/marque_1.png",
      "/projects/fashion/marque_2.png",
      "/projects/fashion/marque_3.png",
      "/projects/fashion/marque_4.png",
      "/projects/fashion/marque_5.png",
      "/projects/fashion/marque_6.png",
    ],
    btsImages: [
      "/projects/fashion/bts/01.jpg",
      "/projects/fashion/bts/02.jpg",
      "/projects/fashion/bts/03.jpg",
      "/projects/fashion/bts/04.jpg",
      "/projects/fashion/bts/05.jpg",
      "/projects/fashion/bts/06.jpg",
      "/projects/fashion/bts/07.jpg",
      "/projects/fashion/bts/08.jpg",
      "/projects/fashion/bts/09.jpg",
      "/projects/fashion/bts/010.jpg",
      "/projects/fashion/bts/011.jpg",
      "/projects/fashion/bts/012.jpg",
      "/projects/fashion/bts/013.jpg",
    ],
  },
  {
    id: 4,
    title: "Forest Touch Calendar",
    caption: "Artistry Amidst Adversity",
    slug: "calendar",
    about:
      " A vivid showcase of fashion, music and style , envisioned and executed entirely on our property, this calendar shoot was a labor of love – from music production to costume design – came together to embody our creative vision.",
    services: [" Campaign Shoot", "Music Production", "Costume Design"],
    description1:
      "During the pandemic, when campaigns were halted due to restrictions, we aimed to showcase the farmhouse's natural allure despite the challenges.",
    description2:
      "Our team's unwavering willpower overcame all hurdles, delivering artistry with global appeal and standing together to exceed expectations against the greatest of odds.",
    bannerImageDesktop: "/projects/calender/banner.jpg",
    bannerImageMobile: "/projects/calender/verticalbanner.jpg",
    aboutImage1: "/projects/calender/1.jpg",
    aboutImage2: "/projects/calender/2.jpg",
    desktopVideos: ["/projects/calender/1.mp4", "/projects/calender/2.mp4"],
    marqueeImage: [
      "/projects/calender/marque_1.jpg",
      "/projects/calender/marque_2.jpg",
      "/projects/calender/marque_3.jpg",
      "/projects/calender/marque_4.jpg",
      "/projects/calender/marque_5.jpg",
      "/projects/calender/marque_6.jpg",
    ],
  },
  {
    id: 5,
    title: "Forest Touch",
    caption: "The essence of Nature’s finest",
    slug: "forest-touch",
    about:
      " Through deep alignment with Forest Touch's eco-centric philosophy, we provided a holistic branding and digital solution, capturing nature’s essence in every detail.",
    services: [
      "Branding",
      "Social Media Management",
      "Website Development",
      "Marketing Strategy",
      "Packaging Design",
      "Photography ",
      "Videography",
    ],
    description1:
      " We embraced the task of making this premium organic food brand accessible, narrating their belief in pure organics .",
    description2:
      "Our team delivered complete 360-degree branding solutions—from packaging to social media— with cohesive storytelling.",
    bannerImageDesktop: "/projects/forest_touch/Forest Touch_Banner.jpg",
    bannerImageMobile:
      "/projects/forest_touch/Forest Touch_Banner Vertical.jpg",
    aboutImage1: "/projects/forest_touch/1.jpg",
    aboutImage2: "/projects/forest_touch/2.jpg",
    marqueeImage: [
      "/projects/forest_touch/Forest Touch_Scrolling 1.jpg",
      "/projects/forest_touch/Forest Touch_Scrolling 2.jpg",
      "/projects/forest_touch/Forest Touch_Scrolling 3.jpg",
      "/projects/forest_touch/Forest Touch_Scrolling 4.jpg",
      "/projects/forest_touch/Forest Touch_Scrolling 5.jpg",
      "/projects/forest_touch/Forest Touch_Scrolling 6.jpg",
    ],
  },
  {
    id: 6,
    title: "Urban Ladder",
    caption: " Design Meets Storytelling",
    slug: "urban-ladder",
    about:
      "By showcasing each product as a piece of art, we were fortunate to collaborate with Urban Ladder to elevate home aesthetics by creating visual content that brings their design ethos and craftsmanship to the forefront.",
    services: ["Product Photography", " Videography"],
    description1:
      "Faced with the challenge of showcasing intricate craftsmanship, we seamlessly blended artistic direction with functionality, enhancing the brand's appeal in modern home decor.",
    description2:
      "Our flexible approach across all social media platforms ensured a successful advertising campaign, meeting client expectations flawlessly.",
    bannerImageDesktop: "/projects/urban_ladder/banner_2.jpg",
    bannerImageMobile: "/projects/urban_ladder/Urban.jpg",
    aboutImage1: "/projects/urban_ladder/1.jpg",
    aboutImage2: "/projects/urban_ladder/2.jpg",
    desktopVideos: ["/projects/urban_ladder/Urbanladder_horizontal_1.mp4"],
    mobileVideos: [
      "/projects/urban_ladder/Urbanladder_vertical_1.mp4",
      "/projects/urban_ladder/Urbanladder_vertical_2.mp4",
    ],
    marqueeImage: [
      "/projects/urban_ladder/Urban Ladder_Scrolling 1.jpg",
      "/projects/urban_ladder/Urban Ladder_Scrolling 2.jpg",
      "/projects/urban_ladder/Urban Ladder_Scrolling 3.jpg",
      "/projects/urban_ladder/Urban Ladder_Scrolling 4.jpg",
      "/projects/urban_ladder/Urban Ladder_Scrolling 5.jpg",
      "/projects/urban_ladder/Urban Ladder_Scrolling 6.jpg",
    ],
    btsImages: [
      "/projects/urban_ladder/bts/11.jpg",
      "/projects/urban_ladder/bts/12.jpg",
      "/projects/urban_ladder/bts/13.jpg",
      "/projects/urban_ladder/bts/14.jpg",
      "/projects/urban_ladder/bts/15.jpg",
      "/projects/urban_ladder/bts/16.jpg",
    ],
  },
  {
    id: 7,
    title: "Art Legends",
    caption: "Spaces Transformed into Art",
    slug: "art-legends",
    about:
      "Working with Art Legends allowed us to delve into a world of style and sophistication , inspiring customers to transform their spaces with an aesthetic that blends timeless elegance and modern artistry.",
    services: ["Product Photography ,Catalogue", "Editorial", "Lifestyle"],
    description1:
      " Challenged to reflect their unique aesthetic and commitment to quality, we showcased a diverse range of elegant furnishings and intricate pieces.",
    description2:
      "​​We ensured each photograph blended style and functionality, fulfilling the client's vision.",
    bannerImageDesktop: "/projects/art_legends/Banner.jpg",
    bannerImageMobile: "/projects/art_legends/Art Legends_Banner Vertical.jpg",
    aboutImage1: "/projects/art_legends/1.jpg",
    aboutImage2: "/projects/art_legends/2.jpg",
    marqueeImage: [
      "/projects/art_legends/Art Legends_Scrolling 1.jpg",
      "/projects/art_legends/Art Legends_Scrolling 2.jpg",
      "/projects/art_legends/Art Legends_Scrolling 3.jpg",
      "/projects/art_legends/Art Legends_Scrolling 4.jpg",
      "/projects/art_legends/Art Legends_Scrolling 5.jpg",
      "/projects/art_legends/Art Legends_Scrolling 6.jpg",
    ],
  },
];
